version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf

  mlflow:
    build: .
    container_name: mlflow
    expose:
      - 5000
