version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd

  mlflow:
    build: .
    container_name: mlflow
    ports:
      - "5000:5000"
